<?php

declare(strict_types=1);

/**
 * @file
 * Provides a deletion record entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function audit_theme(): array {
  return [
    'deletion_record' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for deletion record templates.
 *
 * Default template: deletion-record.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the deletion record information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_deletion_record(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

